-- Starting product list, generated from src/data/produce.js.
-- Run after schema.sql. Re-running only adds missing products; it never
-- overwrites edits made on the admin page.
insert into public.products (id, kind, category, name, name_te, name_hi, emoji, seasonal, sort) values
  ('tomato', 'vegetable', 'everyday', 'Tomato', 'టమాటా', 'टमाटर', '🍅', false, 10),
  ('onion', 'vegetable', 'aromatics', 'Onion', 'ఉల్లిపాయ', 'प्याज', '🧅', false, 20),
  ('potato', 'vegetable', 'roots', 'Potato', 'బంగాళదుంప', 'आलू', '🥔', false, 30),
  ('brinjal', 'vegetable', 'everyday', 'Brinjal', 'వంకాయ', 'बैंगन', '🍆', false, 40),
  ('okra', 'vegetable', 'everyday', 'Okra', 'బెండకాయ', 'भिंडी', '🌿', true, 50),
  ('cauliflower', 'vegetable', 'cabbage-family', 'Cauliflower', 'కాలీఫ్లవర్', 'फूलगोभी', '🥦', true, 60),
  ('cabbage', 'vegetable', 'cabbage-family', 'Cabbage', 'క్యాబేజీ', 'पत्तागोभी', '🥬', false, 70),
  ('carrot', 'vegetable', 'roots', 'Carrot', 'క్యారెట్', 'गाजर', '🥕', false, 80),
  ('beetroot', 'vegetable', 'roots', 'Beetroot', 'బీట్‌రూట్', 'चुकंदर', '🍠', false, 90),
  ('cucumber', 'vegetable', 'everyday', 'Cucumber', 'దోసకాయ', 'खीरा', '🥒', false, 100),
  ('bottle-gourd', 'vegetable', 'gourds', 'Bottle Gourd', 'సొరకాయ', 'लौकी', '🥒', false, 110),
  ('ridge-gourd', 'vegetable', 'gourds', 'Ridge Gourd', 'బీరకాయ', 'तोरई', '🥒', true, 120),
  ('capsicum', 'vegetable', 'everyday', 'Capsicum', 'క్యాప్సికం', 'शिमला मिर्च', '🫑', false, 130),
  ('cluster-beans', 'vegetable', 'beans', 'Cluster Beans', 'గోరు చిక్కుడు', 'ग्वार फली', '🫘', true, 140),
  ('green-chilli', 'vegetable', 'everyday', 'Green Chilli', 'పచ్చిమిర్చి', 'हरी मिर्च', '🌶️', false, 150),
  ('raw-banana', 'vegetable', 'everyday', 'Raw Banana', 'అరటికాయ', 'कच्चा केला', '🍌', false, 160),
  ('radish', 'vegetable', 'roots', 'Radish', 'ముల్లంగి', 'मूली', '🌱', true, 170),
  ('sweet-potato', 'vegetable', 'roots', 'Sweet Potato', 'చిలగడదుంప', 'शकरकंद', '🍠', true, 180),
  ('yam', 'vegetable', 'roots', 'Yam', 'కంద', 'जिमीकंद', '🥔', false, 190),
  ('colocasia', 'vegetable', 'roots', 'Colocasia', 'చామదుంప', 'अरबी', '🥔', true, 200),
  ('garlic', 'vegetable', 'aromatics', 'Garlic', 'వెల్లుల్లి', 'लहसुन', '🧄', false, 210),
  ('ginger', 'vegetable', 'aromatics', 'Ginger', 'అల్లం', 'अदरक', '🫚', false, 220),
  ('spring-onion', 'vegetable', 'aromatics', 'Spring Onion', 'ఉల్లికాడలు', 'हरा प्याज', '🌱', true, 230),
  ('bitter-gourd', 'vegetable', 'gourds', 'Bitter Gourd', 'కాకరకాయ', 'करेला', '🥒', true, 240),
  ('snake-gourd', 'vegetable', 'gourds', 'Snake Gourd', 'పొట్లకాయ', 'चिचिंडा', '🥒', true, 250),
  ('ivy-gourd', 'vegetable', 'gourds', 'Ivy Gourd', 'దొండకాయ', 'कुंदरू', '🥒', false, 260),
  ('ash-gourd', 'vegetable', 'gourds', 'Ash Gourd', 'బూడిద గుమ్మడికాయ', 'पेठा', '🥒', false, 270),
  ('pumpkin', 'vegetable', 'gourds', 'Pumpkin', 'గుమ్మడికాయ', 'कद्दू', '🥒', false, 280),
  ('broccoli', 'vegetable', 'cabbage-family', 'Broccoli', 'బ్రోకలీ', 'ब्रोकली', '🥦', true, 290),
  ('french-beans', 'vegetable', 'beans', 'French Beans', 'బీన్స్', 'फ्रेंच बीन्स', '🫛', false, 300),
  ('peas', 'vegetable', 'beans', 'Green Peas', 'బఠాణీ', 'मटर', '🫛', true, 310),
  ('drumstick', 'vegetable', 'beans', 'Drumstick', 'మునగకాయ', 'सहजन', '🌿', true, 320),
  ('curry-leaves', 'leafy', null, 'Curry Leaves', 'కరివేపాకు', 'करी पत्ता', '🌿', false, 330),
  ('coriander', 'leafy', null, 'Coriander', 'కొత్తిమీర', 'धनिया', '🌿', false, 340),
  ('mint', 'leafy', null, 'Mint', 'పుదీనా', 'पुदीना', '🌱', false, 350),
  ('spinach', 'leafy', null, 'Spinach', 'పాలకూర', 'पालक', '🥬', false, 360),
  ('methi', 'leafy', null, 'Fenugreek Leaves', 'మెంతికూర', 'मेथी', '🌿', true, 370),
  ('dill', 'leafy', null, 'Dill Leaves', 'సబ్బసిగ్గ ఆకు', 'सोआ', '🌿', true, 380),
  ('amaranth', 'leafy', null, 'Amaranth Leaves', 'తోటకూర', 'चौलाई', '🌿', true, 390),
  ('drumstick-leaves', 'leafy', null, 'Drumstick Leaves', 'మునగాకు', 'सहजन के पत्ते', '🌿', true, 400),
  ('gongura', 'leafy', null, 'Gongura (Sorrel)', 'గోంగూర', 'पितवा', '🌿', true, 410),
  ('chukka-kura', 'leafy', null, 'Chukka Kura (Sorrel)', 'చుక్కకూర', 'खट्टा पालक', '🌿', true, 420)
on conflict (id) do nothing;
